### ISSUE TITLE
Some sounds are stereo

### ISSUE THREAD

**Issue by FractalGeodes** [spaghettube/Eclectic_Sounds#1]
The sounds for item pickup and ambient lava are stereo sounds and not mono sounds. 
Minecraft plays stereo sounds 2-dimensionally, and it is always at the player. This causes issues, as even if the sound is quite far away, it still sounds quite close to the player.
It should be a quick fix, just making the audio files each have a singular mono track instead of stereo tracks.
We would pull request instead of make an issue, but because the source is just a zip file instead of being unpacked in the repository, we are refraining from doing so to prevent any merge conflicts.

Other than that, we're loving the pack so far, and are excited to see what new sounds come soon.

Edit: I found some more sounds that have this issue, so I will make a list of them here:
- Item pickup
- Ambient lava
- Critical hit
- Eating burp

**Comment by pocinhas** [comment]
Hey there, thanks for the report.
I actually did not know about the stereo/mono thing, but now that I think about it it makes sense. I'll do some research, edit some sounds and release a new version with the fix soon ;)

Also, about the source, I'm not exactly an expert on Github, this would be my very first experience on uploading stuff here so I'll also search up how I would go about properly uploading my project to make it so pull requests would be a viable option. Thanks for commenting on that too.

**Comment by pocinhas** [comment]
Issue dealt with, will release a new version now. And also thanks for the kind words and appreciating the pack enough to open an issue, means a lot to me <3
