### ISSUE TITLE
Permission to use Eclectic Sounds

### ISSUE THREAD

**Issue by cjtganzon** [spaghettube/Eclectic_Sounds#3]
Hi,
I made a modpack named Immersive Survival on Modrinth aimed at creating a more immersive and ambient experience. I am currently creating a texture/resource pack to fit the style of the modpack feeling animated and adventurous and I think a lot of the sounds from your resource pack would be a great addition to the custom resource pack. May I have your permission to use many of the sounds inside of the custom pack? Credits will be given inside the pack and on the front page and I can also add you as a project member.
- CJ

**Comment by pocinhas** [comment]
Hey. I'll give you the permission yea, no problem. As long as you follow the conditions you stated on your comment
